import os
import sys

import numpy as np

# Import the module to test. Using the 8.0 version as an example.
sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'dags'))
import frankenagent_8_0_kesselflow


def test_embed_text_shape():
    """Verify that embed_text returns an array of the correct shape."""
    text = "test string"
    result = frankenagent_8_0_kesselflow.embed_text(text)
    assert result.shape == (frankenagent_8_0_kesselflow.EMBED_DIM,), f"Expected shape ({frankenagent_8_0_kesselflow.EMBED_DIM},), got {result.shape}"

def test_embed_text_type():
    """Verify that embed_text returns an array of type float32."""
    text = "test string"
    result = frankenagent_8_0_kesselflow.embed_text(text)
    assert result.dtype == np.float32, f"Expected dtype float32, got {result.dtype}"

def test_embed_text_values():
    """Verify that the embedded text values are within expected range [0, 1] as generated by np.random.rand."""
    text = "test string"
    result = frankenagent_8_0_kesselflow.embed_text(text)
    assert np.all((result >= 0) & (result <= 1)), "Array values should be in [0, 1]"
